### ISSUE TITLE
_layouts/15/news.aspx . how to make it public on other sites!

### ISSUE THREAD

**Issue by Ahedabu** [130s/hut_10sqft#358]
How can I make [ _layouts/15/news.aspx ] public on all other sites?

Or let a web part of the news has specific permissions on other sites?

I have main site call **A** has news web part and I can see it all on this path as well:

https://x.sharepoint.com/sites/A/_layouts/15/news.aspx

Site **A**: https://x.sharepoint.com/sites/A/

and site **B** under **A**

Site **B**: https://x.sharepoint.com/sites/A/B

So I want users who are in site **B** to see web part news from site **A** when I have news A's web part inside **B** without letting users from **B** to see the whole site pages on **A**.

**Comment by 130s** [comment]
I do not see any relevance in your description to this repository. Closing.
